language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
sudo: false
install:
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install numpy; fi
  - pip install six
  - pip install redis
  - pip install pyyaml
  - pip install .
script:
  - mkdir _test
  - cd _test
  - nosetests jug
