language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
sudo: false
install:
  - pip install numpy
  - pip install six
  - pip install redis
  - pip install pyyaml
  - pip install .
script:
  - mkdir _test
  - cd _test
  - nosetests jug
